name: Go
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Setup helmfile
      uses: mamezou-tech/setup-helmfile@v0.6.0
      with:
        helmfile-version: "v0.128.1"

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.0.0

    - name: Validate test dependencies
      run: |
        helmfile --version
        helm version
        kubectl version

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: make test

    - name: Build
      run: make build